route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 4h
  receiver: 'telegram-notifications'

receivers:
  - name: 'telegram-notifications'
    telegram_configs:
      - bot_token: '8991662514:AAFOcn908C72sKADmnKfERoDGPndTujZ0Mo'
        chat_id: 6199981598
        send_resolved: true
        parse_mode: 'HTML'
        message: |
          <b>🚨 Clickify Mate Alert: {{ .CommonAnnotations.summary }}</b>
          <b>Severity:</b> {{ .CommonLabels.severity | toUpper }}
          <b>Status:</b> {{ .Status | toUpper }}
          {{ if .CommonAnnotations.description }}
          <b>Details:</b> {{ .CommonAnnotations.description }}
          {{ end }}
