import sys
from pathlib import Path

# Dynamically append the current grpc_stubs folder path to sys.path
# so that python's import system can resolve sibling imports generated by protoc.
current_dir = Path(__file__).resolve().parent
if str(current_dir) not in sys.path:
    sys.path.insert(0, str(current_dir))
