// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.31.1
// source: proto/orchestrator.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentOrchestrator_ProcessEvent_FullMethodName = "/orchestrator.AgentOrchestrator/ProcessEvent"
	AgentOrchestrator_CheckStock_FullMethodName   = "/orchestrator.AgentOrchestrator/CheckStock"
)

// AgentOrchestratorClient is the client API for AgentOrchestrator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentOrchestratorClient interface {
	// Processes an incoming social platform event (WhatsApp, Telegram, Facebook)
	ProcessEvent(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (*EventResponse, error)
	// Queries product inventory stock status
	CheckStock(ctx context.Context, in *StockRequest, opts ...grpc.CallOption) (*StockResponse, error)
}

type agentOrchestratorClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentOrchestratorClient(cc grpc.ClientConnInterface) AgentOrchestratorClient {
	return &agentOrchestratorClient{cc}
}

func (c *agentOrchestratorClient) ProcessEvent(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (*EventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventResponse)
	err := c.cc.Invoke(ctx, AgentOrchestrator_ProcessEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentOrchestratorClient) CheckStock(ctx context.Context, in *StockRequest, opts ...grpc.CallOption) (*StockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StockResponse)
	err := c.cc.Invoke(ctx, AgentOrchestrator_CheckStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentOrchestratorServer is the server API for AgentOrchestrator service.
// All implementations must embed UnimplementedAgentOrchestratorServer
// for forward compatibility.
type AgentOrchestratorServer interface {
	// Processes an incoming social platform event (WhatsApp, Telegram, Facebook)
	ProcessEvent(context.Context, *EventRequest) (*EventResponse, error)
	// Queries product inventory stock status
	CheckStock(context.Context, *StockRequest) (*StockResponse, error)
	mustEmbedUnimplementedAgentOrchestratorServer()
}

// UnimplementedAgentOrchestratorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentOrchestratorServer struct{}

func (UnimplementedAgentOrchestratorServer) ProcessEvent(context.Context, *EventRequest) (*EventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessEvent not implemented")
}
func (UnimplementedAgentOrchestratorServer) CheckStock(context.Context, *StockRequest) (*StockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckStock not implemented")
}
func (UnimplementedAgentOrchestratorServer) mustEmbedUnimplementedAgentOrchestratorServer() {}
func (UnimplementedAgentOrchestratorServer) testEmbeddedByValue()                           {}

// UnsafeAgentOrchestratorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentOrchestratorServer will
// result in compilation errors.
type UnsafeAgentOrchestratorServer interface {
	mustEmbedUnimplementedAgentOrchestratorServer()
}

func RegisterAgentOrchestratorServer(s grpc.ServiceRegistrar, srv AgentOrchestratorServer) {
	// If the following call panics, it indicates UnimplementedAgentOrchestratorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentOrchestrator_ServiceDesc, srv)
}

func _AgentOrchestrator_ProcessEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentOrchestratorServer).ProcessEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentOrchestrator_ProcessEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentOrchestratorServer).ProcessEvent(ctx, req.(*EventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentOrchestrator_CheckStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentOrchestratorServer).CheckStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentOrchestrator_CheckStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentOrchestratorServer).CheckStock(ctx, req.(*StockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentOrchestrator_ServiceDesc is the grpc.ServiceDesc for AgentOrchestrator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentOrchestrator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "orchestrator.AgentOrchestrator",
	HandlerType: (*AgentOrchestratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessEvent",
			Handler:    _AgentOrchestrator_ProcessEvent_Handler,
		},
		{
			MethodName: "CheckStock",
			Handler:    _AgentOrchestrator_CheckStock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/orchestrator.proto",
}
