# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import orchestrator_pb2 as proto_dot_orchestrator__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/orchestrator_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentOrchestratorStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessEvent = channel.unary_unary(
                '/orchestrator.AgentOrchestrator/ProcessEvent',
                request_serializer=proto_dot_orchestrator__pb2.EventRequest.SerializeToString,
                response_deserializer=proto_dot_orchestrator__pb2.EventResponse.FromString,
                _registered_method=True)
        self.CheckStock = channel.unary_unary(
                '/orchestrator.AgentOrchestrator/CheckStock',
                request_serializer=proto_dot_orchestrator__pb2.StockRequest.SerializeToString,
                response_deserializer=proto_dot_orchestrator__pb2.StockResponse.FromString,
                _registered_method=True)


class AgentOrchestratorServicer:
    """Missing associated documentation comment in .proto file."""

    def ProcessEvent(self, request, context):
        """Processes an incoming social platform event (WhatsApp, Telegram, Facebook)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckStock(self, request, context):
        """Queries product inventory stock status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentOrchestratorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessEvent,
                    request_deserializer=proto_dot_orchestrator__pb2.EventRequest.FromString,
                    response_serializer=proto_dot_orchestrator__pb2.EventResponse.SerializeToString,
            ),
            'CheckStock': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckStock,
                    request_deserializer=proto_dot_orchestrator__pb2.StockRequest.FromString,
                    response_serializer=proto_dot_orchestrator__pb2.StockResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'orchestrator.AgentOrchestrator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('orchestrator.AgentOrchestrator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentOrchestrator:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orchestrator.AgentOrchestrator/ProcessEvent',
            proto_dot_orchestrator__pb2.EventRequest.SerializeToString,
            proto_dot_orchestrator__pb2.EventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orchestrator.AgentOrchestrator/CheckStock',
            proto_dot_orchestrator__pb2.StockRequest.SerializeToString,
            proto_dot_orchestrator__pb2.StockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
