# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/orchestrator.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'proto/orchestrator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18proto/orchestrator.proto\x12\x0corchestrator\"\x94\x01\n\x0c\x45ventRequest\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x10\n\x08platform\x18\x02 \x01(\t\x12\x10\n\x08\x61gent_id\x18\x03 \x01(\t\x12\x11\n\tsender_id\x18\x04 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x05 \x01(\t\x12\x14\n\x0cmessage_type\x18\x06 \x01(\t\x12\x14\n\x0cpayload_json\x18\x07 \x01(\t\"`\n\rEventResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x12\n\nreply_text\x18\x02 \x01(\t\x12\x13\n\x0btokens_used\x18\x03 \x01(\x05\x12\x15\n\rerror_message\x18\x04 \x01(\t\"\x1b\n\x0cStockRequest\x12\x0b\n\x03sku\x18\x01 \x01(\t\"K\n\rStockResponse\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05stock\x18\x03 \x01(\x05\x12\r\n\x05price\x18\x04 \x01(\x01\x32\xa3\x01\n\x11\x41gentOrchestrator\x12G\n\x0cProcessEvent\x12\x1a.orchestrator.EventRequest\x1a\x1b.orchestrator.EventResponse\x12\x45\n\nCheckStock\x12\x1a.orchestrator.StockRequest\x1a\x1b.orchestrator.StockResponseBBZ@clickify-mate/services/orchestrator/internal/transport/grpc;grpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.orchestrator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z@clickify-mate/services/orchestrator/internal/transport/grpc;grpc'
  _globals['_EVENTREQUEST']._serialized_start=43
  _globals['_EVENTREQUEST']._serialized_end=191
  _globals['_EVENTRESPONSE']._serialized_start=193
  _globals['_EVENTRESPONSE']._serialized_end=289
  _globals['_STOCKREQUEST']._serialized_start=291
  _globals['_STOCKREQUEST']._serialized_end=318
  _globals['_STOCKRESPONSE']._serialized_start=320
  _globals['_STOCKRESPONSE']._serialized_end=395
  _globals['_AGENTORCHESTRATOR']._serialized_start=398
  _globals['_AGENTORCHESTRATOR']._serialized_end=561
# @@protoc_insertion_point(module_scope)
