# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import verifier_pb2 as proto_dot_verifier__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/verifier_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ImageVerifierStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.VerifyReceipt = channel.unary_unary(
                '/verifier.ImageVerifier/VerifyReceipt',
                request_serializer=proto_dot_verifier__pb2.VerifyRequest.SerializeToString,
                response_deserializer=proto_dot_verifier__pb2.VerifyResponse.FromString,
                _registered_method=True)


class ImageVerifierServicer:
    """Missing associated documentation comment in .proto file."""

    def VerifyReceipt(self, request, context):
        """Checks payment receipt image bytes, validates authenticity, and extracts transaction identifiers
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageVerifierServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'VerifyReceipt': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyReceipt,
                    request_deserializer=proto_dot_verifier__pb2.VerifyRequest.FromString,
                    response_serializer=proto_dot_verifier__pb2.VerifyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'verifier.ImageVerifier', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('verifier.ImageVerifier', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ImageVerifier:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def VerifyReceipt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/verifier.ImageVerifier/VerifyReceipt',
            proto_dot_verifier__pb2.VerifyRequest.SerializeToString,
            proto_dot_verifier__pb2.VerifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
