# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/verifier.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'proto/verifier.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14proto/verifier.proto\x12\x08verifier\"P\n\rVerifyRequest\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x14\n\x0cimage_base64\x18\x02 \x01(\t\x12\x17\n\x0f\x65xpected_amount\x18\x03 \x01(\x01\"\x82\x01\n\x0eVerifyResponse\x12\x10\n\x08is_valid\x18\x01 \x01(\x08\x12\x16\n\x0etransaction_id\x18\x02 \x01(\t\x12\x17\n\x0f\x61mount_detected\x18\x03 \x01(\x01\x12\x16\n\x0ehash_signature\x18\x04 \x01(\t\x12\x15\n\rerror_message\x18\x05 \x01(\t2S\n\rImageVerifier\x12\x42\n\rVerifyReceipt\x12\x17.verifier.VerifyRequest\x1a\x18.verifier.VerifyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.verifier_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VERIFYREQUEST']._serialized_start=34
  _globals['_VERIFYREQUEST']._serialized_end=114
  _globals['_VERIFYRESPONSE']._serialized_start=117
  _globals['_VERIFYRESPONSE']._serialized_end=247
  _globals['_IMAGEVERIFIER']._serialized_start=249
  _globals['_IMAGEVERIFIER']._serialized_end=332
# @@protoc_insertion_point(module_scope)
